### ISSUE TITLE
Microhex-js fails to install with error

### ISSUE THREAD

**Issue by ldhacker** [zenwarr/microhex-js#1]
When trying to install Microhex, I get the following error with `npm install`:

```
3675 timing command:install Completed in 18255ms
3676 verbose stack Error: command failed
3676 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
3676 verbose stack     at ChildProcess.emit (node:events:365:28)
3676 verbose stack     at maybeClose (node:internal/child_process:1067:16)
3676 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
3677 verbose pkgid electron@1.8.3
3678 verbose cwd /Users/dustinhacker/Downloads/microhex-js-master
3679 verbose Darwin 20.4.0
3680 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
3681 verbose node v16.0.0
3682 verbose npm  v7.11.2
3683 error code 1
3684 error path /Users/dustinhacker/Downloads/microhex-js-master/node_modules/electron
3685 error command failed
3686 error command sh -c node install.js
3687 error Downloading electron-v1.8.3-darwin-arm64.zip
3687 error [>                                            ] 0.0% (0 B/s)
3687 error [1000D[0K[1A[1000D[0K[1A[1000D[0KDownloading electron-v1.8.3-darwin-arm64.zip
3687 error Error: GET https://github.com/electron/electron/releases/download/v1.8.3/electron-v1.8.3-darwin-arm64.zip returned 404
3688 error /Users/dustinhacker/Downloads/microhex-js-master/node_modules/electron/install.js:47
3688 error   throw err
3688 error   ^
3688 error
3688 error Error: Failed to find Electron v1.8.3 for darwin-arm64 at https://github.com/electron/electron/releases/download/v1.8.3/electron-v1.8.3-darwin-arm64.zip
3688 error     at Request.<anonymous> (/Users/dustinhacker/Downloads/microhex-js-master/node_modules/nugget/index.js:169:61)
3688 error     at Request.emit (node:events:365:28)
3688 error     at Request.onRequestResponse (/Users/dustinhacker/Downloads/microhex-js-master/node_modules/request/request.js:1068:10)
3688 error     at ClientRequest.emit (node:events:365:28)
3688 error     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:621:27)
3688 error     at HTTPParser.parserOnHeadersComplete (node:_http_common:127:17)
3688 error     at TLSSocket.socketOnData (node:_http_client:487:22)
3688 error     at TLSSocket.emit (node:events:365:28)
3688 error     at addChunk (node:internal/streams/readable:314:12)
3688 error     at readableAddChunk (node:internal/streams/readable:289:9)
3689 verbose exit 1
```

I have electron installed as the latest version. But it seems to want to try and download it anyway.
[2021-04-30T04_38_31_710Z-debug.log](https://github.com/zenwarr/microhex-js/files/6403050/2021-04-30T04_38_31_710Z-debug.log)

**Comment by zenwarr** [comment]
It was built on a pretty old version of electron (and it didn't have binaries for arm mac back then) and probably won't work with a new one, even if you install it locally. You could try to run it on linux with node v6 if you want. But I don't think the project worth the hassle: it was a little experiment and is now long abandoned. I'm going to archive the repository, thanks for your interest.
